/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JDesktopPane;

/**
 *
 * @author Gustavo Santos
 */
public class FormMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormMenuPrincipal
     */
    public FormMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenuPrincipal = new javax.swing.JPanel();
        DesktopPaneMenuPrincipal = new javax.swing.JDesktopPane();
        labelIdFuncionarioLogado = new javax.swing.JLabel();
        labelNomeFuncionarioLogado = new javax.swing.JLabel();
        formMenuPrincipalMenuBar = new javax.swing.JMenuBar();
        relatorioMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        consultarMenu = new javax.swing.JMenu();
        consultarEstoqueMenuItem = new javax.swing.JMenuItem();
        consultarClienteMenuItem = new javax.swing.JMenuItem();
        consultarFuncionarioMenuItem = new javax.swing.JMenuItem();
        cadastrarMenu = new javax.swing.JMenu();
        cadastrarClienteMenuItem = new javax.swing.JMenuItem();
        cadastrarProdutoMenuItem = new javax.swing.JMenuItem();
        cadastrarFuncionarioMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);
        setSize(new java.awt.Dimension(944, 577));

        panelMenuPrincipal.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout DesktopPaneMenuPrincipalLayout = new javax.swing.GroupLayout(DesktopPaneMenuPrincipal);
        DesktopPaneMenuPrincipal.setLayout(DesktopPaneMenuPrincipalLayout);
        DesktopPaneMenuPrincipalLayout.setHorizontalGroup(
            DesktopPaneMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
        );
        DesktopPaneMenuPrincipalLayout.setVerticalGroup(
            DesktopPaneMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        labelIdFuncionarioLogado.setBackground(new java.awt.Color(255, 255, 255));
        labelIdFuncionarioLogado.setForeground(new java.awt.Color(255, 255, 255));
        labelIdFuncionarioLogado.setText("#");

        labelNomeFuncionarioLogado.setForeground(new java.awt.Color(255, 255, 255));
        labelNomeFuncionarioLogado.setText(".");

        javax.swing.GroupLayout panelMenuPrincipalLayout = new javax.swing.GroupLayout(panelMenuPrincipal);
        panelMenuPrincipal.setLayout(panelMenuPrincipalLayout);
        panelMenuPrincipalLayout.setHorizontalGroup(
            panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPaneMenuPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuPrincipalLayout.createSequentialGroup()
                .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNomeFuncionarioLogado)
                    .addComponent(labelIdFuncionarioLogado))
                .addGap(66, 66, 66))
        );
        panelMenuPrincipalLayout.setVerticalGroup(
            panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelIdFuncionarioLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNomeFuncionarioLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DesktopPaneMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        relatorioMenu.setText("Relatório");

        jMenuItem1.setText("Simples");
        relatorioMenu.add(jMenuItem1);

        jMenuItem2.setText("Completo");
        relatorioMenu.add(jMenuItem2);

        formMenuPrincipalMenuBar.add(relatorioMenu);

        consultarMenu.setText("Consultar");

        consultarEstoqueMenuItem.setText("Estoque");
        consultarMenu.add(consultarEstoqueMenuItem);

        consultarClienteMenuItem.setText("Cliente");
        consultarMenu.add(consultarClienteMenuItem);

        consultarFuncionarioMenuItem.setText("Funcionário");
        consultarMenu.add(consultarFuncionarioMenuItem);

        formMenuPrincipalMenuBar.add(consultarMenu);

        cadastrarMenu.setText("Cadastrar");

        cadastrarClienteMenuItem.setText("Cliente");
        cadastrarMenu.add(cadastrarClienteMenuItem);

        cadastrarProdutoMenuItem.setText("Produto");
        cadastrarProdutoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarProdutoMenuItemActionPerformed(evt);
            }
        });
        cadastrarMenu.add(cadastrarProdutoMenuItem);

        cadastrarFuncionarioMenuItem.setText("Funcionário");
        cadastrarFuncionarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncionarioMenuItemActionPerformed(evt);
            }
        });
        cadastrarMenu.add(cadastrarFuncionarioMenuItem);

        formMenuPrincipalMenuBar.add(cadastrarMenu);

        setJMenuBar(formMenuPrincipalMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarProdutoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarProdutoMenuItemActionPerformed
        CadastroProduto cadastroProduto = new CadastroProduto();
        cadastroProduto.setVisible(true);
        DesktopPaneMenuPrincipal.add(cadastroProduto);
        cadastroProduto.pack();
    }//GEN-LAST:event_cadastrarProdutoMenuItemActionPerformed

    private void cadastrarFuncionarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionarioMenuItemActionPerformed
        CadastroFuncionario cadastroFuncionario = new CadastroFuncionario();
        cadastroFuncionario.setVisible(true);
        DesktopPaneMenuPrincipal.add(cadastroFuncionario);
        cadastroFuncionario.pack();
    }//GEN-LAST:event_cadastrarFuncionarioMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPaneMenuPrincipal;
    private javax.swing.JMenuItem cadastrarClienteMenuItem;
    private javax.swing.JMenuItem cadastrarFuncionarioMenuItem;
    private javax.swing.JMenu cadastrarMenu;
    private javax.swing.JMenuItem cadastrarProdutoMenuItem;
    private javax.swing.JMenuItem consultarClienteMenuItem;
    private javax.swing.JMenuItem consultarEstoqueMenuItem;
    private javax.swing.JMenuItem consultarFuncionarioMenuItem;
    private javax.swing.JMenu consultarMenu;
    private javax.swing.JMenuBar formMenuPrincipalMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel labelIdFuncionarioLogado;
    private javax.swing.JLabel labelNomeFuncionarioLogado;
    private javax.swing.JPanel panelMenuPrincipal;
    private javax.swing.JMenu relatorioMenu;
    // End of variables declaration//GEN-END:variables
}
