/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Gustavo Santos
 */
public class GerarPedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form GerarPedido
     */
    public GerarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        panelPedido = new javax.swing.JPanel();
        panelEstante = new javax.swing.JPanel();
        labelCpfClientePedido = new javax.swing.JLabel();
        frmtTextCpfClientePedido = new javax.swing.JFormattedTextField();
        scrollPaneEstanteProdutosPedidos = new javax.swing.JScrollPane();
        tableEstanteProdutosPedidos = new javax.swing.JTable();
        buttonBuscarProdutoPedido = new javax.swing.JButton();
        comboBoxTipoProdutoPedido = new javax.swing.JComboBox<>();
        comboBoxCategoriaProdutoPedido = new javax.swing.JComboBox<>();
        textFieldCodigoProdutoPedido = new javax.swing.JTextField();
        labelCodidoProdutoPedido = new javax.swing.JLabel();
        labelCategoriaProdutoPedido = new javax.swing.JLabel();
        labelTipoProdutoPedido = new javax.swing.JLabel();
        panelCarrinhoPedido = new javax.swing.JPanel();
        scrollPaneCarrinhoPedido = new javax.swing.JScrollPane();
        tableCarrinhoPedido = new javax.swing.JTable();
        labelTotalPedido = new javax.swing.JLabel();
        textFieldTotalPedido = new javax.swing.JTextField();
        labelDescontoPedido = new javax.swing.JLabel();
        textFieldAplicarDescontoPedido = new javax.swing.JTextField();
        buttonFinalizarPedido = new javax.swing.JButton();
        buttonCancelarPedido = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Gerar Pedido");

        panelPedido.setBackground(new java.awt.Color(255, 255, 255));

        panelEstante.setBackground(new java.awt.Color(255, 255, 255));
        panelEstante.setBorder(javax.swing.BorderFactory.createTitledBorder("Estante"));

        labelCpfClientePedido.setText("CPF CLIENTE *");

        try {
            frmtTextCpfClientePedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        tableEstanteProdutosPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID do Produto", "Marca", "Modelo", "Descrição", "Preço Un"
            }
        ));
        scrollPaneEstanteProdutosPedidos.setViewportView(tableEstanteProdutosPedidos);

        buttonBuscarProdutoPedido.setText("BUSCAR");

        comboBoxTipoProdutoPedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione -" }));

        comboBoxCategoriaProdutoPedido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione -" }));

        labelCodidoProdutoPedido.setText("CODIGO DO PRODUTO");

        labelCategoriaProdutoPedido.setText("CATEGORIA");

        labelTipoProdutoPedido.setText("TIPO");

        javax.swing.GroupLayout panelEstanteLayout = new javax.swing.GroupLayout(panelEstante);
        panelEstante.setLayout(panelEstanteLayout);
        panelEstanteLayout.setHorizontalGroup(
            panelEstanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEstanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneEstanteProdutosPedidos)
                    .addGroup(panelEstanteLayout.createSequentialGroup()
                        .addGroup(panelEstanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCpfClientePedido)
                            .addComponent(frmtTextCpfClientePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelEstanteLayout.createSequentialGroup()
                                .addGroup(panelEstanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCodidoProdutoPedido)
                                    .addComponent(textFieldCodigoProdutoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelEstanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxCategoriaProdutoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCategoriaProdutoPedido))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelEstanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTipoProdutoPedido)
                                    .addGroup(panelEstanteLayout.createSequentialGroup()
                                        .addComponent(comboBoxTipoProdutoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonBuscarProdutoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 220, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelEstanteLayout.setVerticalGroup(
            panelEstanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEstanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCpfClientePedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(frmtTextCpfClientePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEstanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodidoProdutoPedido)
                    .addComponent(labelCategoriaProdutoPedido)
                    .addComponent(labelTipoProdutoPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEstanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonBuscarProdutoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldCodigoProdutoPedido)
                    .addComponent(comboBoxCategoriaProdutoPedido)
                    .addComponent(comboBoxTipoProdutoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneEstanteProdutosPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelCarrinhoPedido.setBackground(new java.awt.Color(255, 255, 255));
        panelCarrinhoPedido.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrinho"));

        tableCarrinhoPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID do Produto", "Marca", "Modelo", "Descrição", "Quantidade", "Preço Un"
            }
        ));
        scrollPaneCarrinhoPedido.setViewportView(tableCarrinhoPedido);

        labelTotalPedido.setText("TOTAL");

        textFieldTotalPedido.setEnabled(false);

        labelDescontoPedido.setText("DESCONTO");

        buttonFinalizarPedido.setText("FINALIZAR PEDIDO");

        buttonCancelarPedido.setText("CANCELAR");

        javax.swing.GroupLayout panelCarrinhoPedidoLayout = new javax.swing.GroupLayout(panelCarrinhoPedido);
        panelCarrinhoPedido.setLayout(panelCarrinhoPedidoLayout);
        panelCarrinhoPedidoLayout.setHorizontalGroup(
            panelCarrinhoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarrinhoPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCarrinhoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneCarrinhoPedido)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCarrinhoPedidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelCarrinhoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCarrinhoPedidoLayout.createSequentialGroup()
                                .addGroup(panelCarrinhoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldAplicarDescontoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDescontoPedido))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelCarrinhoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTotalPedido)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCarrinhoPedidoLayout.createSequentialGroup()
                                .addComponent(buttonCancelarPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonFinalizarPedido)))))
                .addContainerGap())
        );
        panelCarrinhoPedidoLayout.setVerticalGroup(
            panelCarrinhoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCarrinhoPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneCarrinhoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCarrinhoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCarrinhoPedidoLayout.createSequentialGroup()
                        .addComponent(labelTotalPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCarrinhoPedidoLayout.createSequentialGroup()
                        .addComponent(labelDescontoPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldAplicarDescontoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelCarrinhoPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFinalizarPedido)
                    .addComponent(buttonCancelarPedido))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelPedidoLayout = new javax.swing.GroupLayout(panelPedido);
        panelPedido.setLayout(panelPedidoLayout);
        panelPedidoLayout.setHorizontalGroup(
            panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEstante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCarrinhoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPedidoLayout.setVerticalGroup(
            panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelEstante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCarrinhoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscarProdutoPedido;
    private javax.swing.JButton buttonCancelarPedido;
    private javax.swing.JButton buttonFinalizarPedido;
    private javax.swing.JComboBox<String> comboBoxCategoriaProdutoPedido;
    private javax.swing.JComboBox<String> comboBoxTipoProdutoPedido;
    private javax.swing.JFormattedTextField frmtTextCpfClientePedido;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelCategoriaProdutoPedido;
    private javax.swing.JLabel labelCodidoProdutoPedido;
    private javax.swing.JLabel labelCpfClientePedido;
    private javax.swing.JLabel labelDescontoPedido;
    private javax.swing.JLabel labelTipoProdutoPedido;
    private javax.swing.JLabel labelTotalPedido;
    private javax.swing.JPanel panelCarrinhoPedido;
    private javax.swing.JPanel panelEstante;
    private javax.swing.JPanel panelPedido;
    private javax.swing.JScrollPane scrollPaneCarrinhoPedido;
    private javax.swing.JScrollPane scrollPaneEstanteProdutosPedidos;
    private javax.swing.JTable tableCarrinhoPedido;
    private javax.swing.JTable tableEstanteProdutosPedidos;
    private javax.swing.JTextField textFieldAplicarDescontoPedido;
    private javax.swing.JTextField textFieldCodigoProdutoPedido;
    private javax.swing.JTextField textFieldTotalPedido;
    // End of variables declaration//GEN-END:variables
}
